language: go
arch: amd64
virt: vm
os: linux
dist: focal
go:
  - "1.24"

cache:
  directories:
    - $HOME/.cache/go-build # Cache the binaries
    - $HOME/gopath/pkg/mod # Cache the Go modules

services:
  - docker

stages:
  - lint
  - test

before_install:
  - export GO111MODULE=on
  - export GOPRIVATE=github.ibm.com
  - export DB_DEPLOYMENT=local
  - git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.ibm.com".insteadOf "https://github.ibm.com"

jobs:
  include:
    - stage: lint
      install:
        # Install dependencies
        - scripts/install-protobuf.sh
        - go install golang.org/x/tools/cmd/goimports@latest
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.0.2
        - pip install sqlfluff
      before_script:
        # Fetch main to only detect issues from changes to main
        - git fetch origin main:main
        # Apply formatting
        - find . -name \*.go -not -name \*.pb.go -exec goimports -d -e -local "github.ibm.com/decentralized-trust-research/scalable-committer" {} \; | tee /dev/stderr | [ $(wc -c) -eq 0 ]
        - find . -name \*.go -not -name \*.pb.go -exec gofmt -d -e  {} \; | tee /dev/stderr | [ $(wc -c) -eq 0 ]
        - PATH="$HOME/bin:$PATH" make proto
      script:
        # Check if original code changed due to formatting
        - git diff | tee /dev/stderr | [ $(wc -c) -eq 0 ]
        # Run lint and test
        - make lint
    - stage: test
      name: Unit Test (non DB)
      script: make test-non-db-packages
    - stage: test
      name: Unit Tests (postgres)
      install: scripts/get-and-start-postgres.sh
      script: make test-db-packages
    - stage: test
      name: Unit Tests (yugabyte)
      install: scripts/get-and-start-yuga.sh
      script: make test-db-packages
    - stage: test
      name: Integration Tests (yugabyte)
      install: scripts/get-and-start-yuga.sh
      script: travis_wait 30 make integration-test
    - stage: test
      name: Build and test container images
      script: make container-test -j16
