# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: $PROM_URL
    isDefault: true
    access: proxy
    editable: true