server:
  endpoint: {{ .ServerEndpoint | default "localhost:0" }}
  server-creds:
    use-tls: "{{ .ServiceTLS.UseTLS }}"
    mutual-tls: "{{ .ServiceTLS.MutualTLS }}"
    cert-path: "{{ .ServiceTLS.PublicKeyPath }}"
    key-path: "{{ .ServiceTLS.PrivateKeyPath }}"
    ca-cert-path: "{{ .ServiceTLS.CACertificatePath }}"
monitoring:
  server:
    endpoint: {{ .MetricsEndpoint | default "localhost:0" }}

sign-verifier:
  server:
    {{- range .Endpoints.Verifier }}
    - endpoint: {{ . }}
    {{- end }}
validator-committer:
  server:
   {{- range .Endpoints.VCService }}
    - endpoint: {{ . }}
    {{- end }}
dependency-graph:
  num-of-local-dep-constructors: 1
  waiting-txs-limit: 10_000
  num-of-workers-for-global-dep-manager: 1
  # Add monitoring configuration here if applicable
per-channel-buffer-size-per-goroutine: 10

logging:
  enabled: {{ .Logging.Enabled }}
  level: {{ .Logging.Level }}
  caller: {{ .Logging.Caller }}
  development: {{ .Logging.Development }}
  output: {{ .Logging.Output }}
  name: coordinator
