server:
  endpoint: {{ .ServerEndpoint | default "localhost:0" }}
  server-creds:
    use-tls: "{{ .ServiceTLS.UseTLS }}"
    mutual-tls: "{{ .ServiceTLS.MutualTLS }}"
    cert-path: "{{ .ServiceTLS.Credentials.CertPath }}"
    key-path: "{{ .ServiceTLS.Credentials.KeyPath }}"
    ca-cert-path: "{{ .ServiceTLS.Credentials.CACertPath }}"
monitoring:
  server:
    endpoint: {{ .MetricsEndpoint | default "localhost:0" }}

sign-verifier:
  server:
    {{- range $i, $endpoint := .Endpoints.Verifier }}
      {{- $tls := index $.VcAndSigTLSConfig.SigClientsConfig $i }}
      - endpoint: {{ $endpoint }}
        server-creds:
          use-tls: "{{ $tls.UseTLS }}"
          mutual-tls: "{{ $tls.MutualTLS }}"
          key-path: "{{ $tls.Credentials.KeyPath }}"
          cert-path: "{{ $tls.Credentials.CertPath }}"
          ca-cert-path: "{{ $tls.Credentials.CACertPath }}"
      {{- end }}

validator-committer:
  server:
    {{- range $i, $endpoint := .Endpoints.VCService }}
      {{- $tls := index $.VcAndSigTLSConfig.VcClientsConfig $i }}
      - endpoint: {{ $endpoint }}
        server-creds:
          use-tls: "{{ $tls.UseTLS }}"
          mutual-tls: "{{ $tls.MutualTLS }}"
          key-path: "{{ $tls.Credentials.KeyPath }}"
          cert-path: "{{ $tls.Credentials.CertPath }}"
          ca-cert-path: "{{ $tls.Credentials.CACertPath }}"
      {{- end }}

dependency-graph:
  num-of-local-dep-constructors: 1
  waiting-txs-limit: 10_000
  num-of-workers-for-global-dep-manager: 1
  # Add monitoring configuration here if applicable
per-channel-buffer-size-per-goroutine: 10

logging:
  enabled: {{ .Logging.Enabled }}
  level: {{ .Logging.Level }}
  caller: {{ .Logging.Caller }}
  development: {{ .Logging.Development }}
  output: {{ .Logging.Output }}
  name: coordinator
