# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
server:
  endpoint: {{ .ServiceEndpoints.Server | default "localhost:0" }}
  server-creds:
    tls-mode: {{ .ServiceTLS.Mode }}
    server-name: {{ .ServiceTLS.ServerName }}
    cert-path: {{ .ServiceTLS.CertPath }}
    key-path: {{ .ServiceTLS.KeyPath }}
    ca-cert-paths:
      {{- range .ServiceTLS.CACertPaths }}
      - {{ . }}
      {{- end }}

monitoring:
  server:
    endpoint: {{ .ServiceEndpoints.Metrics | default "localhost:0" }}

verifier:
  endpoints:
    {{- range .Endpoints.Verifier }}
    - {{ .Server }}
    {{- end }}
  client-creds:
    tls-mode: {{ .ClientsCreds.Verifier.Mode }}
    server-name: {{ .ClientsCreds.Verifier.ServerName }}
    key-path: {{ .ClientsCreds.Verifier.KeyPath }}
    cert-path: {{ .ClientsCreds.Verifier.CertPath }}
    ca-cert-paths:
      {{- range .ClientsCreds.Verifier.CACertPaths }}
      - {{ . }}
      {{- end }}

validator-committer:
  endpoints:
    {{- range .Endpoints.VCService }}
    - {{ .Server }}
    {{- end }}
  client-creds:
    tls-mode: {{ .ClientsCreds.Vc.Mode }}
    server-name: {{ .ClientsCreds.Vc.ServerName }}
    key-path: {{ .ClientsCreds.Vc.KeyPath }}
    cert-path: {{ .ClientsCreds.Vc.CertPath }}
    ca-cert-paths:
      {{- range .ClientsCreds.Vc.CACertPaths }}
      - {{ . }}
      {{- end }}

dependency-graph:
  num-of-local-dep-constructors: 1
  waiting-txs-limit: 10_000
  num-of-workers-for-global-dep-manager: 1
  # Add monitoring configuration here if applicable
per-channel-buffer-size-per-goroutine: 10

logging:
  enabled: {{ .Logging.Enabled }}
  level: {{ .Logging.Level }}
  caller: {{ .Logging.Caller }}
  development: {{ .Logging.Development }}
  output: {{ .Logging.Output }}
  name: coordinator
