server:
  endpoint: {{ .ServiceEndpoints.Server | default "localhost:0" }}
  server-creds:
    use-tls: {{ .ServiceTLS.UseTLS }}
    mutual-tls: {{ .ServiceTLS.MutualTLS }}
    cert-path: "{{ .ServiceTLS.Credentials.CertPath }}"
    key-path: "{{ .ServiceTLS.Credentials.KeyPath }}"
    ca-cert-paths:
      {{- range .ServiceTLS.Credentials.CACertPaths }}
      - "{{ . }}"
      {{- end }}

monitoring:
  server:
    endpoint: {{ .ServiceEndpoints.Metrics | default "localhost:0" }}

verifier:
  endpoints:
    {{- range .Endpoints.Verifier }}
    - {{ .Server }}
    {{- end }}
  server-creds:
    {{- range .VcAndSigTLSConfig.SigClientsConfig }}
    - use-tls: {{ .UseTLS }}
      mutual-tls: {{ .MutualTLS }}
      key-path: "{{ .Credentials.KeyPath }}"
      cert-path: "{{ .Credentials.CertPath }}"
      ca-cert-paths:
        {{- range .Credentials.CACertPaths }}
        - "{{ . }}"
        {{- end }}
    {{- end }}

validator-committer:
  endpoints:
    {{- range .Endpoints.VCService }}
    - {{ .Server }}
    {{- end }}
  server-creds:
    {{- range .VcAndSigTLSConfig.VcClientsConfig }}
    - use-tls: {{ .UseTLS }}
      mutual-tls: {{ .MutualTLS }}
      key-path: "{{ .Credentials.KeyPath }}"
      cert-path: "{{ .Credentials.CertPath }}"
      ca-cert-paths:
        {{- range .Credentials.CACertPaths }}
        - "{{ . }}"
        {{- end }}
    {{- end }}

dependency-graph:
  num-of-local-dep-constructors: 1
  waiting-txs-limit: 10000
  num-of-workers-for-global-dep-manager: 1

per-channel-buffer-size-per-goroutine: 10

logging:
  enabled: {{ .Logging.Enabled }}
  level: {{ .Logging.Level }}
  caller: {{ .Logging.Caller }}
  development: {{ .Logging.Development }}
  output: {{ .Logging.Output }}
  name: coordinator
