# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
server:
  endpoint: {{ .ServiceEndpoints.Server | default "localhost:0" }}
  tls:
    mode: {{ .ServiceCreds.Mode }}
    cert-path: {{ .ServiceCreds.CertPath }}
    key-path: {{ .ServiceCreds.KeyPath }}
    ca-cert-paths:
      {{- range .ServiceCreds.CACertPaths }}
      - {{ . }}
      {{- end }}

monitoring:
  server:
    endpoint: {{ .ServiceEndpoints.Metrics | default "localhost:0" }}

verifier:
  endpoints:
    {{- range .Endpoints.Verifier }}
    - {{ .Server }}
    {{- end }}
  tls: &ClientCreds
    mode: {{ .ClientCreds.Mode }}
    key-path: {{ .ClientCreds.KeyPath }}
    cert-path: {{ .ClientCreds.CertPath }}
    ca-cert-paths:
      {{- range .ClientCreds.CACertPaths }}
      - {{ . }}
      {{- end }}

validator-committer:
  endpoints:
   {{- range .Endpoints.VCService }}
    - {{ .Server }}
   {{- end }}
  tls:
    *ClientCreds

dependency-graph:
  num-of-local-dep-constructors: 1
  waiting-txs-limit: 100_000
  # Add monitoring configuration here if applicable
per-channel-buffer-size-per-goroutine: 10

logging:
  enabled: {{ .Logging.Enabled }}
  level: {{ .Logging.Level }}
  caller: {{ .Logging.Caller }}
  development: {{ .Logging.Development }}
  output: {{ .Logging.Output }}
  name: coordinator
