# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# This is a partial template. It contains only the VC client configurations.
# It should be complimented by the common load generator configuration.

vc-client:
  endpoints:
    {{- range .Endpoints.VCService }}
    - {{ .Server }}
    {{- end }}
  tls:
    mode: {{ .ClientTLS.Mode }}
    key-path: {{ .ClientTLS.KeyPath }}
    cert-path: {{ .ClientTLS.CertPath }}
    ca-cert-paths:
      {{- range .ClientTLS.CACertPaths }}
      - {{ . }}
      {{- end }}
