# This is a partial template. It contains only the orderer client configurations.
# It should be complimented by the common load generator configuration.

orderer-client:
  sidecar-endpoint: {{ .Endpoints.Sidecar.Server }}
  sidecar-tls-config:
    use-tls: "{{ .SidecarClientTLSConfig.UseTLS }}"
    mutual-tls: "{{ .SidecarClientTLSConfig.MutualTLS }}"
    cert-path: "{{ .SidecarClientTLSConfig.Credentials.CertPath }}"
    key-path: "{{ .SidecarClientTLSConfig.Credentials.KeyPath }}"
    ca-cert-paths:
      {{- range .SidecarClientTLSConfig.Credentials.CACertPaths }}
      - "{{ . }}"
      {{- end }}
  orderer:
    connection:
      endpoints:
        {{- range .Endpoints.Orderer }}
        - {{ .Server }}
        {{- end }}
    consensus-type: BFT
    channel-id: {{ .ChannelID }}
  broadcast-parallelism: 50
