# This is a partial template. It contains only the sidecar client configurations.
# It should be complimented by the common load generator configuration.

sidecar-client:
  sidecar-client-config:
    endpoint: {{ .Endpoints.Sidecar.Server }}
    server-creds:
      use-tls: {{ .SidecarClientTLSConfig.UseTLS }}
      mutual-tls: {{ .SidecarClientTLSConfig.MutualTLS }}
      server-name: {{ .SidecarClientTLSConfig.ServerName }}
      cert-path: "{{ .SidecarClientTLSConfig.CertPath }}"
      key-path: "{{ .SidecarClientTLSConfig.KeyPath }}"
      ca-cert-paths:
        {{- range .SidecarClientTLSConfig.CACertPaths }}
        - "{{ . }}"
        {{- end }}
  orderer-servers:
    {{- range .Endpoints.Orderer }}
    - endpoint: {{ .Server }}
    {{- end }}
  channel-id: {{ .ChannelID }}
