# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# This is a partial template. It contains only the coordinator client configurations.
# It should be complimented by the common load generator configuration.

coordinator-client:
  endpoints:
    - {{ .Endpoints.Coordinator.Server }}
  client-creds:
    tls-mode: {{ .ClientsCreds.Coordinator.Mode }}
    server-name: {{ .ClientsCreds.Coordinator.ServerName }}
    key-path: {{ .ClientsCreds.Coordinator.KeyPath }}
    cert-path: {{ .ClientsCreds.Coordinator.CertPath }}
    ca-cert-paths:
      {{- range .ClientsCreds.Coordinator.CACertPaths }}
      - {{ . }}
      {{- end }}
