# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# This is a partial template. It contains only the sidecar client configurations.
# It should be complimented by the common load generator configuration.

sidecar-client:
  sidecar-client-config:
    endpoints:
      - {{ .Endpoints.Sidecar.Server }}
    client-creds:
      tls-mode: {{ .ClientsConfig.Sidecar.Mode }}
      server-name: {{ .ClientsConfig.Sidecar.ServerName }}
      cert-path: {{ .ClientsConfig.Sidecar.CertPath }}
      key-path: {{ .ClientsConfig.Sidecar.KeyPath }}
      ca-cert-paths:
        {{- range .ClientsConfig.Sidecar.CACertPaths }}
        - {{ . }}
        {{- end }}
  orderer-servers:
    {{- range .Endpoints.Orderer }}
    - endpoint: {{ .Server }}
    {{- end }}
  channel-id: {{ .ChannelID }}
