# This is a partial template. It contains only the orderer client configurations.
# It should be complimented by the common load generator configuration.

orderer-client:
  sidecar-client-config:
    endpoint: {{ .Endpoints.Sidecar.Server }}
    server-creds:
      use-tls: {{ .SidecarClientTLSConfig.UseTLS }}
      mutual-tls: {{ .SidecarClientTLSConfig.MutualTLS }}
      server-name: {{ .SidecarClientTLSConfig.ServerName }}
      cert-path: "{{ .SidecarClientTLSConfig.CertPath }}"
      key-path: "{{ .SidecarClientTLSConfig.KeyPath }}"
      ca-cert-paths:
        {{- range .SidecarClientTLSConfig.CACertPaths }}
        - "{{ . }}"
        {{- end }}
  orderer:
    connection:
      endpoints:
        {{- range .Endpoints.Orderer }}
        - {{ .Server }}
        {{- end }}
    consensus-type: BFT
    channel-id: {{ .ChannelID }}
  broadcast-parallelism: 50
