# This is a partial template. It contains only the sidecar client configurations.
# It should be complimented by the common load generator configuration.

sidecar-client:
  sidecar-client-config:
    endpoint: {{ .Endpoints.Sidecar.Server }}
    server-creds:
      use-tls: {{ .ClientsConfig.Sidecar.UseTLS }}
      mutual-tls: {{ .ClientsConfig.Sidecar.MutualTLS }}
      server-name: {{ .ClientsConfig.Sidecar.ServerName }}
      cert-path: {{ .ClientsConfig.Sidecar.CertPath }}
      key-path: {{ .ClientsConfig.Sidecar.KeyPath }}
      ca-cert-paths:
        {{- range .ClientsConfig.Sidecar.CACertPaths }}
        - "{{ . }}"
        {{- end }}
  orderer-servers:
    {{- range .Endpoints.Orderer }}
    - endpoint: {{ .Server }}
    {{- end }}
  channel-id: {{ .ChannelID }}
