# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# This is a partial template. It contains only the coordinator client configurations.
# It should be complimented by the common load generator configuration.

coordinator-client:
  endpoints:
    - {{ .Endpoints.Coordinator.Server }}
  reconnect:
    lb-policy: pick_first
  tls:
    mode: {{ .ClientTLS.Mode }}
    key-path: {{ .ClientTLS.KeyPath }}
    cert-path: {{ .ClientTLS.CertPath }}
    ca-cert-paths:
      {{- range .ClientTLS.CACertPaths }}
      - {{ . }}
      {{- end }}
