# This is a partial template. It contains only the orderer client configurations.
# It should be complimented by the common load generator configuration.

orderer-client:
  sidecar-client-config:
    endpoint: {{ .Endpoints.Sidecar.Server }}
    server-creds:
      use-tls: {{ .ClientsConfig.Sidecar.UseTLS }}
      mutual-tls: {{ .ClientsConfig.Sidecar.MutualTLS }}
      server-name: {{ .ClientsConfig.Sidecar.ServerName }}
      cert-path: {{ .ClientsConfig.Sidecar.CertPath }}
      key-path: {{ .ClientsConfig.Sidecar.KeyPath }}
      ca-cert-paths:
        {{- range .ClientsConfig.Sidecar.CACertPaths }}
        - "{{ . }}"
        {{- end }}
  orderer:
    connection:
      endpoints:
        {{- range .Endpoints.Orderer }}
        - {{ .Server }}
        {{- end }}
    consensus-type: BFT
    channel-id: {{ .ChannelID }}
  broadcast-parallelism: 50
