# This is a partial template. It contains only the sidecar client configurations.
# It should be complimented by the common load generator configuration.

sidecar-client:
  sidecar-endpoint: {{ .Endpoints.Sidecar.Server }}
  sidecar-tls-config:
    use-tls: "{{ .SidecarClientTLSConfig.UseTLS }}"
    mutual-tls: "{{ .SidecarClientTLSConfig.MutualTLS }}"
    cert-path: "{{ .SidecarClientTLSConfig.Credentials.CertPath }}"
    key-path: "{{ .SidecarClientTLSConfig.Credentials.KeyPath }}"
    ca-cert-paths:
      {{- range .SidecarClientTLSConfig.Credentials.CACertPaths }}
      - "{{ . }}"
      {{- end }}
  orderer-servers:
    {{- range .Endpoints.Orderer }}
    - endpoint: {{ .Server }}
    {{- end }}
  channel-id: {{ .ChannelID }}
