servers:
  {{- range .Endpoints.Orderer }}
  - endpoint: {{ .Server }}
  {{- end }}
block-size: {{ .BlockSize }}
block-timeout: {{ .BlockTimeout }}
config-block-path: {{ .ConfigBlockPath }}
send-config-block: true

logging:
  enabled: {{ .Logging.Enabled }}
  level: {{ .Logging.Level }}
  caller: {{ .Logging.Caller }}
  development: {{ .Logging.Development }}
  output: {{ .Logging.Output }}
  name: orderer
