# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Configuration for the server
server:
  endpoint: {{ .ServiceEndpoints.Server | default "localhost:0" }}
  server-creds:
    tls-mode: {{ .ServiceCreds.Mode }}
    server-name: {{ .ServiceCreds.ServerName }}
    cert-path: {{ .ServiceCreds.CertPath }}
    key-path: {{ .ServiceCreds.KeyPath }}
    ca-cert-paths:
      {{- range .ServiceCreds.CACertPaths }}
      - {{ . }}
      {{- end }}
monitoring:
  server:
    endpoint: {{ .ServiceEndpoints.Metrics | default "localhost:0" }}

database:
  endpoints:
    {{- range .DB.Endpoints }}
    - {{ . }}
    {{- end }}
  username: "yugabyte"
  # TODO: pass password via environment variable
  password: "yugabyte"
  database: {{ .DB.Name }}
  load-balance: {{ .DB.LoadBalance }}
  max-connections: 10
  min-connections: 5
  retry:
    max-elapsed-time: 1h

logging:
  enabled: {{ .Logging.Enabled }}
  level: {{ .Logging.Level }}
  caller: {{ .Logging.Caller }}
  development: {{ .Logging.Development }}
  output: {{ .Logging.Output }}
  name: query
