# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
server:
  endpoint: {{ .ServiceEndpoints.Server | default "localhost:0" }}
  creds:
    tls-mode: {{ .ServiceCreds.Mode }}
    server-name: {{ .ServiceCreds.ServerName }}
    cert-path: {{ .ServiceCreds.CertPath }}
    key-path: {{ .ServiceCreds.KeyPath }}
    ca-cert-paths:
      {{- range .ServiceCreds.CACertPaths }}
      - {{ . }}
      {{- end }}
  keep-alive:
    params:
      time: 300s
      timeout: 600s
    enforcement-policy:
      min-time: 60s
      permit-without-stream: false
monitoring:
  server:
    endpoint: {{ .ServiceEndpoints.Metrics | default "localhost:0" }}

orderer:
  connection:
    endpoints:
      {{- range .Endpoints.Orderer }}
      - {{ .Server }}
      {{- end }}
  channel-id: {{ .ChannelID }}
  consensus-type: BFT
committer:
  endpoints:
    - {{ .Endpoints.Coordinator.Server }}
  creds:
    tls-mode: {{ .ClientsCreds.Coordinator.Mode }}
    server-name: {{ .ClientsCreds.Coordinator.ServerName }}
    cert-path: {{ .ClientsCreds.Coordinator.CertPath }}
    key-path: {{ .ClientsCreds.Coordinator.KeyPath }}
    ca-cert-paths:
      {{- range .ClientsCreds.Coordinator.CACertPaths }}
      - {{ . }}
      {{- end }}

ledger:
  path: {{ .LedgerPath }}

last-committed-block-set-interval: 5s
waiting-txs-limit: 20_000_000

bootstrap:
  genesis-block-file-path: {{ .ConfigBlockPath }}

logging:
  enabled: {{ .Logging.Enabled }}
  level: {{ .Logging.Level }}
  caller: {{ .Logging.Caller }}
  development: {{ .Logging.Development }}
  output: {{ .Logging.Output }}
  name: sidecar
