server:
  endpoint: {{ .ServiceEndpoints.Server | default "localhost:0" }}
  server-creds:
    use-tls: {{ .ServiceTLS.UseTLS }}
    mutual-tls: {{ .ServiceTLS.MutualTLS }}
    server-name: {{ .ServiceTLS.ServerName }}
    cert-path: "{{ .ServiceTLS.CertPath }}"
    key-path: "{{ .ServiceTLS.KeyPath }}"
    ca-cert-paths:
      {{- range .ServiceTLS.CACertPaths }}
      - "{{ . }}"
      {{- end }}
  keep-alive:
    params:
      time: 300s
      timeout: 600s
    enforcement-policy:
      min-time: 60s
      permit-without-stream: false
monitoring:
  server:
    endpoint: {{ .ServiceEndpoints.Metrics | default "localhost:0" }}

orderer:
  connection:
    endpoints:
      {{- range .Endpoints.Orderer }}
      - {{ .Server }}
      {{- end }}
  channel-id: {{ .ChannelID }}
  consensus-type: BFT
committer:
  client:
    endpoint: {{ .Endpoints.Coordinator.Server }}
    server-creds:
      use-tls: {{ .CoordinatorClientTLSConfig.UseTLS }}
      mutual-tls: {{ .CoordinatorClientTLSConfig.MutualTLS }}
      server-name: {{ .CoordinatorClientTLSConfig.ServerName }}
      cert-path: "{{ .CoordinatorClientTLSConfig.CertPath }}"
      key-path: "{{ .CoordinatorClientTLSConfig.KeyPath }}"
      ca-cert-paths:
        {{- range .CoordinatorClientTLSConfig.CACertPaths }}
        - "{{ . }}"
        {{- end }}

ledger:
  path: {{ .LedgerPath }}

last-committed-block-set-interval: 5s

bootstrap:
  genesis-block-file-path: {{ .ConfigBlockPath }}

logging:
  enabled: {{ .Logging.Enabled }}
  level: {{ .Logging.Level }}
  caller: {{ .Logging.Caller }}
  development: {{ .Logging.Development }}
  output: {{ .Logging.Output }}
  name: sidecar
