server:
  endpoint: {{ .ServerEndpoint | default "localhost:0" }}
  server-creds:
    use-tls: "{{ .ServiceTLS.UseTLS }}"
    mutual-tls: "{{ .ServiceTLS.MutualTLS }}"
    cert-path: "{{ .ServiceTLS.Credentials.CertPath }}"
    key-path: "{{ .ServiceTLS.Credentials.KeyPath }}"
    ca-cert-path: "{{ .ServiceTLS.Credentials.CACertPath }}"
  keep-alive:
    params:
      time: 300s
      timeout: 600s
    enforcement-policy:
      min-time: 60s
      permit-without-stream: false
monitoring:
  server:
    endpoint: {{ .MetricsEndpoint | default "localhost:0" }}

orderer:
  connection:
    endpoints:
      {{- range .Endpoints.Orderer }}
      - {{ . }}
      {{- end }}
  channel-id: {{ .ChannelID }}
  consensus-type: BFT
committer:
  server:
    endpoint: {{ .Endpoints.Coordinator }}
    server-creds:
      use-tls: "{{ .CoordinatorClientTLSConfig.UseTLS }}"
      mutual-tls: "{{ .CoordinatorClientTLSConfig.MutualTLS }}"
      cert-path: "{{ .CoordinatorClientTLSConfig.Credentials.CertPath }}"
      key-path: "{{ .CoordinatorClientTLSConfig.Credentials.KeyPath }}"
      ca-cert-path: "{{ .CoordinatorClientTLSConfig.Credentials.CACertPath }}"

ledger:
  path: {{ .LedgerPath }}

last-committed-block-set-interval: 5s

bootstrap:
  genesis-block-file-path: {{ .ConfigBlockPath }}

logging:
  enabled: {{ .Logging.Enabled }}
  level: {{ .Logging.Level }}
  caller: {{ .Logging.Caller }}
  development: {{ .Logging.Development }}
  output: {{ .Logging.Output }}
  name: sidecar
