server:
  endpoint: {{ .ServiceEndpoints.Server | default "localhost:0" }}
  server-creds:
    use-tls: {{ .ServiceTLS.UseTLS }}
    mutual-tls: {{ .ServiceTLS.MutualTLS }}
    server-name: {{ .ServiceTLS.ServerName }}
    cert-path: "{{ .ServiceTLS.CertPath }}"
    key-path: "{{ .ServiceTLS.KeyPath }}"
    ca-cert-paths:
      {{- range .ServiceTLS.CACertPaths }}
      - "{{ . }}"
      {{- end }}

monitoring:
  server:
    endpoint: {{ .ServiceEndpoints.Metrics | default "localhost:0" }}

parallel-executor:
  parallelism: 40
  batch-time-cutoff: 10ms
  batch-size-cutoff: 50
  channel-buffer-size: 50

logging:
  enabled: {{ .Logging.Enabled }}
  level: {{ .Logging.Level }}
  caller: {{ .Logging.Caller }}
  development: {{ .Logging.Development }}
  output: {{ .Logging.Output }}
  name: verifier
