server:
  endpoint: {{ .ServerEndpoint | default "localhost:0" }}
  server-creds:
    use-tls: "{{ .ServiceTLS.UseTLS }}"
    mutual-tls: "{{ .ServiceTLS.MutualTLS }}"
    cert-path: "{{ .ServiceTLS.Credentials.CertPath }}"
    key-path: "{{ .ServiceTLS.Credentials.KeyPath }}"
    ca-cert-path: "{{ .ServiceTLS.Credentials.CACertPath }}"
monitoring:
  server:
    endpoint: {{ .MetricsEndpoint | default "localhost:0" }}

parallel-executor:
  parallelism: 40
  batch-time-cutoff: 10ms
  batch-size-cutoff: 50
  channel-buffer-size: 50

logging:
  enabled: {{ .Logging.Enabled }}
  level: {{ .Logging.Level }}
  caller: {{ .Logging.Caller }}
  development: {{ .Logging.Development }}
  output: {{ .Logging.Output }}
  name: verifier
