server:
  endpoint: {{ .ServiceEndpoints.Server | default "localhost:0" }}
  server-creds:
    use-tls: {{ .ServiceTLS.UseTLS }}
    mutual-tls: {{ .ServiceTLS.MutualTLS }}
    server-name: {{ .ServiceTLS.ServerName }}
    cert-path: "{{ .ServiceTLS.CertPath }}"
    key-path: "{{ .ServiceTLS.KeyPath }}"
    ca-cert-paths:
      {{- range .ServiceTLS.CACertPaths }}
      - "{{ . }}"
      {{- end }}

monitoring:
  server:
    endpoint: {{ .ServiceEndpoints.Metrics | default "localhost:0" }}

database:
  endpoints:
    {{- range .DB.Endpoints }}
    - {{ . }}
    {{- end }}
  username: "yugabyte"
  # TODO: pass password via environment variable
  password: "yugabyte"
  database: {{ .DB.Name }}
  load-balance: {{ .DB.LoadBalance }}
  max-connections: 10
  min-connections: 5
  retry:
    max-elapsed-time: 1h

resource-limits:
  max-workers-for-preparer: 1
  max-workers-for-validator: 1
  max-workers-for-committer: 20
  min-transaction-batch-size: 1

logging:
  enabled: {{ .Logging.Enabled }}
  level: {{ .Logging.Level }}
  caller: {{ .Logging.Caller }}
  development: {{ .Logging.Development }}
  output: {{ .Logging.Output }}
  name: VC
