//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: api/servicepb/auth.proto

package servicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// signed_envelope is a marshaled common.Envelope carrying the client's serialized MSP identity
	// and a signature over the payload; under mutual TLS its ChannelHeader also carries the TLS
	// certificate hash the token is bound to.
	SignedEnvelope []byte `protobuf:"bytes,1,opt,name=signed_envelope,json=signedEnvelope,proto3" json:"signed_envelope,omitempty"`
	// requested_scope optionally narrows the token's authority (least privilege). A requested scope
	// may only narrow, never broaden, the identity's authority.
	RequestedScope []string `protobuf:"bytes,2,rep,name=requested_scope,json=requestedScope,proto3" json:"requested_scope,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_api_servicepb_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_servicepb_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_api_servicepb_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetSignedEnvelope() []byte {
	if x != nil {
		return x.SignedEnvelope
	}
	return nil
}

func (x *AuthenticateRequest) GetRequestedScope() []string {
	if x != nil {
		return x.RequestedScope
	}
	return nil
}

type AuthenticateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token is the minted cert-bound JWT the client attaches to subsequent RPCs.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// expires_at is the token expiry in unix seconds.
	ExpiresAt     int64 `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_api_servicepb_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_servicepb_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_api_servicepb_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthenticateResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type AuthorizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token is the client's JWT, forwarded by the resource server.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// resource is the gRPC full method being authorized, e.g. "/committerpb.QueryService/GetRows".
	Resource string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// tls_cert_hash is the SHA-256 of the caller's TLS certificate observed at the resource server.
	// It is empty when the caller connected without a client certificate.
	TlsCertHash   []byte `protobuf:"bytes,3,opt,name=tls_cert_hash,json=tlsCertHash,proto3" json:"tls_cert_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_api_servicepb_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_servicepb_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_api_servicepb_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthorizeRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuthorizeRequest) GetTlsCertHash() []byte {
	if x != nil {
		return x.TlsCertHash
	}
	return nil
}

type ReAuthorizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// identity is the MSP SerializedIdentity that Authorize bound to the stream session at
	// establishment. Re-authorization re-resolves it against the latest configuration and evaluates
	// the resource policy again; it deliberately does not re-present the token, so a stream's
	// authorization tracks the identity's live permissions rather than the establishment token's TTL.
	Identity []byte `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// resource is the gRPC full method the stream belongs to.
	Resource      string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReAuthorizeRequest) Reset() {
	*x = ReAuthorizeRequest{}
	mi := &file_api_servicepb_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReAuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReAuthorizeRequest) ProtoMessage() {}

func (x *ReAuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_servicepb_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReAuthorizeRequest.ProtoReflect.Descriptor instead.
func (*ReAuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_api_servicepb_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ReAuthorizeRequest) GetIdentity() []byte {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ReAuthorizeRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type AuthorizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// authorized is true when the identity satisfies the resource policy. The RPCs return a gRPC
	// status error for every non-authorized outcome (Unauthenticated for an invalid, expired, or
	// unknown token or a certificate mismatch; PermissionDenied for a scope or policy denial;
	// Unavailable before the configuration is loaded), so a successful response always has
	// authorized = true.
	Authorized bool `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	// identity is the resolved MSP SerializedIdentity bound to the token. Authorize returns it so a
	// resource server can bind it to a stream session and later pass it to ReAuthorize.
	Identity      []byte `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_api_servicepb_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_servicepb_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_api_servicepb_auth_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorizeResponse) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

func (x *AuthorizeResponse) GetIdentity() []byte {
	if x != nil {
		return x.Identity
	}
	return nil
}

// TokenRecord is the persisted token-to-identity binding, keyed by jti and stored proto-serialized
// in the auth service's identity store. It - not the raw JWT - holds the client's serialized MSP
// identity, so the identity can be re-resolved against the latest configuration at authorization
// time and a token can be revoked by deleting the record.
type TokenRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// jti is the opaque token id and the row key.
	Jti string `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	// serialized_identity is the client's MSP SerializedIdentity.
	SerializedIdentity []byte `protobuf:"bytes,2,opt,name=serialized_identity,json=serializedIdentity,proto3" json:"serialized_identity,omitempty"`
	// msp_id is the client's MSP identifier, kept for logging and quick filtering.
	MspId string `protobuf:"bytes,3,opt,name=msp_id,json=mspId,proto3" json:"msp_id,omitempty"`
	// cert_hash_sha256 is the cnf/x5t#S256 binding to the client's TLS certificate.
	CertHashSha256 []byte `protobuf:"bytes,4,opt,name=cert_hash_sha256,json=certHashSha256,proto3" json:"cert_hash_sha256,omitempty"`
	// scope is the optional least-privilege scope granted at issuance.
	Scope []string `protobuf:"bytes,5,rep,name=scope,proto3" json:"scope,omitempty"`
	// issued_sequence is the config sequence the identity was first resolved against.
	IssuedSequence uint64 `protobuf:"varint,6,opt,name=issued_sequence,json=issuedSequence,proto3" json:"issued_sequence,omitempty"`
	// expires_at is the token expiry in unix seconds, used for TTL cleanup.
	ExpiresAt     int64 `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRecord) Reset() {
	*x = TokenRecord{}
	mi := &file_api_servicepb_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRecord) ProtoMessage() {}

func (x *TokenRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_servicepb_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRecord.ProtoReflect.Descriptor instead.
func (*TokenRecord) Descriptor() ([]byte, []int) {
	return file_api_servicepb_auth_proto_rawDescGZIP(), []int{5}
}

func (x *TokenRecord) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *TokenRecord) GetSerializedIdentity() []byte {
	if x != nil {
		return x.SerializedIdentity
	}
	return nil
}

func (x *TokenRecord) GetMspId() string {
	if x != nil {
		return x.MspId
	}
	return ""
}

func (x *TokenRecord) GetCertHashSha256() []byte {
	if x != nil {
		return x.CertHashSha256
	}
	return nil
}

func (x *TokenRecord) GetScope() []string {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *TokenRecord) GetIssuedSequence() uint64 {
	if x != nil {
		return x.IssuedSequence
	}
	return 0
}

func (x *TokenRecord) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_api_servicepb_auth_proto protoreflect.FileDescriptor

const file_api_servicepb_auth_proto_rawDesc = "" +
	"\n" +
	"\x18api/servicepb/auth.proto\x12\tservicepb\"g\n" +
	"\x13AuthenticateRequest\x12'\n" +
	"\x0fsigned_envelope\x18\x01 \x01(\fR\x0esignedEnvelope\x12'\n" +
	"\x0frequested_scope\x18\x02 \x03(\tR\x0erequestedScope\"K\n" +
	"\x14AuthenticateResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"h\n" +
	"\x10AuthorizeRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\"\n" +
	"\rtls_cert_hash\x18\x03 \x01(\fR\vtlsCertHash\"L\n" +
	"\x12ReAuthorizeRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\fR\bidentity\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\"O\n" +
	"\x11AuthorizeResponse\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\bR\n" +
	"authorized\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\fR\bidentity\"\xef\x01\n" +
	"\vTokenRecord\x12\x10\n" +
	"\x03jti\x18\x01 \x01(\tR\x03jti\x12/\n" +
	"\x13serialized_identity\x18\x02 \x01(\fR\x12serializedIdentity\x12\x15\n" +
	"\x06msp_id\x18\x03 \x01(\tR\x05mspId\x12(\n" +
	"\x10cert_hash_sha256\x18\x04 \x01(\fR\x0ecertHashSha256\x12\x14\n" +
	"\x05scope\x18\x05 \x03(\tR\x05scope\x12'\n" +
	"\x0fissued_sequence\x18\x06 \x01(\x04R\x0eissuedSequence\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt2\xf2\x01\n" +
	"\vAuthService\x12O\n" +
	"\fAuthenticate\x12\x1e.servicepb.AuthenticateRequest\x1a\x1f.servicepb.AuthenticateResponse\x12F\n" +
	"\tAuthorize\x12\x1b.servicepb.AuthorizeRequest\x1a\x1c.servicepb.AuthorizeResponse\x12J\n" +
	"\vReAuthorize\x12\x1d.servicepb.ReAuthorizeRequest\x1a\x1c.servicepb.AuthorizeResponseB9Z7github.com/hyperledger/fabric-x-committer/api/servicepbb\x06proto3"

var (
	file_api_servicepb_auth_proto_rawDescOnce sync.Once
	file_api_servicepb_auth_proto_rawDescData []byte
)

func file_api_servicepb_auth_proto_rawDescGZIP() []byte {
	file_api_servicepb_auth_proto_rawDescOnce.Do(func() {
		file_api_servicepb_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_servicepb_auth_proto_rawDesc), len(file_api_servicepb_auth_proto_rawDesc)))
	})
	return file_api_servicepb_auth_proto_rawDescData
}

var file_api_servicepb_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_servicepb_auth_proto_goTypes = []any{
	(*AuthenticateRequest)(nil),  // 0: servicepb.AuthenticateRequest
	(*AuthenticateResponse)(nil), // 1: servicepb.AuthenticateResponse
	(*AuthorizeRequest)(nil),     // 2: servicepb.AuthorizeRequest
	(*ReAuthorizeRequest)(nil),   // 3: servicepb.ReAuthorizeRequest
	(*AuthorizeResponse)(nil),    // 4: servicepb.AuthorizeResponse
	(*TokenRecord)(nil),          // 5: servicepb.TokenRecord
}
var file_api_servicepb_auth_proto_depIdxs = []int32{
	0, // 0: servicepb.AuthService.Authenticate:input_type -> servicepb.AuthenticateRequest
	2, // 1: servicepb.AuthService.Authorize:input_type -> servicepb.AuthorizeRequest
	3, // 2: servicepb.AuthService.ReAuthorize:input_type -> servicepb.ReAuthorizeRequest
	1, // 3: servicepb.AuthService.Authenticate:output_type -> servicepb.AuthenticateResponse
	4, // 4: servicepb.AuthService.Authorize:output_type -> servicepb.AuthorizeResponse
	4, // 5: servicepb.AuthService.ReAuthorize:output_type -> servicepb.AuthorizeResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_servicepb_auth_proto_init() }
func file_api_servicepb_auth_proto_init() {
	if File_api_servicepb_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_servicepb_auth_proto_rawDesc), len(file_api_servicepb_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_servicepb_auth_proto_goTypes,
		DependencyIndexes: file_api_servicepb_auth_proto_depIdxs,
		MessageInfos:      file_api_servicepb_auth_proto_msgTypes,
	}.Build()
	File_api_servicepb_auth_proto = out.File
	file_api_servicepb_auth_proto_goTypes = nil
	file_api_servicepb_auth_proto_depIdxs = nil
}
