#!/usr/bin/env bash
#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

set -e

ops="${*:-db orderer committer loadgen sigservice vc query coordinator sidecar}"

if [[ $ops == *"db"* ]]; then
  export POSTGRES_PASSWORD=yugabyte
  export POSTGRES_USER=yugabyte
  docker-entrypoint.sh postgres -p 5433 &
fi

if [[ $ops == *"orderer"* ]]; then
  "$BINS_PATH/mock"      start-orderer     --config "$CONFIGS_PATH/mock-orderer.yaml" &
fi

if [[ $ops == *"verifier"* ]]; then
  "$BINS_PATH/committer" start-verifier    --config "$CONFIGS_PATH/sigservice.yaml" &
fi

if [[ $ops == *"vc"* ]]; then
  "$BINS_PATH/committer" start-vc    --config "$CONFIGS_PATH/vcservice.yaml" &
fi

if [[ $ops == *"query"* ]]; then
  "$BINS_PATH/committer" start-query       --config "$CONFIGS_PATH/queryservice.yaml" &
fi

if [[ $ops == *"coordinator"* ]]; then
  "$BINS_PATH/committer" start-coordinator --config "$CONFIGS_PATH/coordinator.yaml" &
fi

if [[ $ops == *"sidecar"* ]]; then
  "$BINS_PATH/committer" start-sidecar     --config "$CONFIGS_PATH/sidecar.yaml" &
fi

if [[ $ops == *"loadgen"* ]]; then
  "$BINS_PATH/loadgen" start --config "$CONFIGS_PATH/loadgen.yaml" &
fi

# This just override's the postgres trap.
function cleanup() {
  jobs
}
trap 'cleanup' SIGINT

wait
echo "Process finished with status $?"
